#******************************************************************************
# ALX - Skies of Arcadia Legends Examiner
# Copyright (C) 2015 Marcel Renner
# 
# This file is part of ALX.
# 
# ALX is free software: you can redistribute it and/or modify it under the 
# terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
# 
# ALX is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
# details.
# 
# You should have received a copy of the GNU General Public License along with 
# ALX. If not, see <http://www.gnu.org/licenses/>.
#******************************************************************************

# -- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --

module ALX

#==============================================================================
#                                    CLASS
#==============================================================================

# Mixin for custom translations.
module Translatable
  
#==============================================================================
#                                  CONSTANTS
#==============================================================================

  # EU names of enemies
  ENEMY_EU_LIST = Hash.new('???')
  ENEMY_EU_LIST.store(  0, 'Ferratus'        )
  ENEMY_EU_LIST.store(  1, 'Praeses'         )
  ENEMY_EU_LIST.store(  2, 'Latro'           )
  ENEMY_EU_LIST.store(  3, 'Marocca'         )
  ENEMY_EU_LIST.store(  4, 'Grouder'         )
  ENEMY_EU_LIST.store(  7, 'Venificus'       )
  ENEMY_EU_LIST.store(  8, 'Flestik'         )
  ENEMY_EU_LIST.store(  9, 'Basallish'       )
  ENEMY_EU_LIST.store( 10, 'Dementis'        )
  ENEMY_EU_LIST.store( 11, 'Walrenk'         )
  ENEMY_EU_LIST.store( 12, 'Varkris'         )
  ENEMY_EU_LIST.store( 13, 'Azbeth'          )
  ENEMY_EU_LIST.store( 14, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store( 15, 'Ghastling'       )
  ENEMY_EU_LIST.store( 16, 'Florast'         )
  ENEMY_EU_LIST.store( 17, 'Tsirat'          )
  ENEMY_EU_LIST.store( 18, 'Thorkyn'         )
  ENEMY_EU_LIST.store( 19, 'Scorfly'         )
  ENEMY_EU_LIST.store( 20, 'Centralk'        )
  ENEMY_EU_LIST.store( 21, 'Feralisk'        )
  ENEMY_EU_LIST.store( 22, 'Ferlith'         )
  ENEMY_EU_LIST.store( 23, 'Crylhound'       )
  ENEMY_EU_LIST.store( 24, 'Magma Tiki'      )
  ENEMY_EU_LIST.store( 25, 'Salamander'      )
  ENEMY_EU_LIST.store( 26, 'Baroo'           )
  ENEMY_EU_LIST.store( 27, 'Oestrus'         )
  ENEMY_EU_LIST.store( 28, 'Deatth'          )
  ENEMY_EU_LIST.store( 29, 'Looper'          )
  ENEMY_EU_LIST.store( 30, 'Loopalon'        )
  ENEMY_EU_LIST.store( 31, 'Tsurak'          )
  ENEMY_EU_LIST.store( 32, 'Enforca'         )
  ENEMY_EU_LIST.store( 33, 'Serpantis'       )
  ENEMY_EU_LIST.store( 34, 'Dralnog'         )
  ENEMY_EU_LIST.store( 35, 'Que\'lak'        )
  ENEMY_EU_LIST.store( 36, 'Pinalisk'        )
  ENEMY_EU_LIST.store( 37, 'Crylbeast'       )
  ENEMY_EU_LIST.store( 38, 'Slothstra'       )
  ENEMY_EU_LIST.store( 39, 'Polraxis'        )
  ENEMY_EU_LIST.store( 40, 'Roseln'          )
  ENEMY_EU_LIST.store( 41, 'Elooper'         )
  ENEMY_EU_LIST.store( 42, 'Grapor'          )
  ENEMY_EU_LIST.store( 43, 'Sphyrus'         )
  ENEMY_EU_LIST.store( 44, 'Iridzu'          )
  ENEMY_EU_LIST.store( 45, 'Flyst'           )
  ENEMY_EU_LIST.store( 46, 'Medullizk'       )
  ENEMY_EU_LIST.store( 47, 'Lucich'          )
  ENEMY_EU_LIST.store( 48, 'Digger'          )
  ENEMY_EU_LIST.store( 49, 'Fiendo'          )
  ENEMY_EU_LIST.store( 50, 'Burocca'         )
  ENEMY_EU_LIST.store( 51, 'Drogerp'         )
  ENEMY_EU_LIST.store( 52, 'Nadnarb'         )
  ENEMY_EU_LIST.store( 53, 'Nairad'          )
  ENEMY_EU_LIST.store( 54, 'Kanezl'          )
  ENEMY_EU_LIST.store( 55, 'Mantoid'         )
  ENEMY_EU_LIST.store( 56, 'Sorcerer'        )
  ENEMY_EU_LIST.store( 57, 'Slithar'         )
  ENEMY_EU_LIST.store( 58, 'Golooper'        )
  ENEMY_EU_LIST.store( 59, 'Alusphere'       )
  ENEMY_EU_LIST.store( 60, 'Mereo'           )
  ENEMY_EU_LIST.store( 61, 'Delzool'         )
  ENEMY_EU_LIST.store( 62, 'Defensor'        )
  ENEMY_EU_LIST.store( 63, 'Ghrost'          )
  ENEMY_EU_LIST.store( 64, 'Graver'          )
  ENEMY_EU_LIST.store( 65, 'Shrilp'          )
  ENEMY_EU_LIST.store( 66, 'Cerosik'         )
  ENEMY_EU_LIST.store( 67, 'Carnilak'        )
  ENEMY_EU_LIST.store( 68, 'Valgand'         )
  ENEMY_EU_LIST.store( 69, 'Berserker'       )
  ENEMY_EU_LIST.store( 70, 'Lurgel Tank'     )
  ENEMY_EU_LIST.store( 71, 'Tenkou'          )
  ENEMY_EU_LIST.store( 72, 'Custos'          )
  ENEMY_EU_LIST.store( 73, 'Fossor'          )
  ENEMY_EU_LIST.store( 74, 'Gelu Vermis'     )
  ENEMY_EU_LIST.store( 75, 'Eversor'         )
  ENEMY_EU_LIST.store( 76, 'Marauder'        )
  ENEMY_EU_LIST.store( 77, 'Susceptor'       )
  ENEMY_EU_LIST.store( 78, 'Telsor'          )
  ENEMY_EU_LIST.store( 79, 'Dorntak'         )
  ENEMY_EU_LIST.store( 80, 'Linark'          )
  ENEMY_EU_LIST.store( 81, 'Dolthstra'       )
  ENEMY_EU_LIST.store( 82, 'Dracolurg'       )
  ENEMY_EU_LIST.store( 83, 'Garagor'         )
  ENEMY_EU_LIST.store( 84, 'Kilite'          )
  ENEMY_EU_LIST.store( 85, 'Imezl'           )
  ENEMY_EU_LIST.store( 86, 'Lurker'          )
  ENEMY_EU_LIST.store( 87, 'Jellikra'        )
  ENEMY_EU_LIST.store( 88, 'Scorpon'         )
  ENEMY_EU_LIST.store( 89, 'Arclooper'       )
  ENEMY_EU_LIST.store( 90, 'Tsorok'          )
  ENEMY_EU_LIST.store( 91, 'Sentree'         )
  ENEMY_EU_LIST.store( 92, 'Langry'          )
  ENEMY_EU_LIST.store( 93, 'Scarabée'        )
  ENEMY_EU_LIST.store( 94, 'Totelm'          )
  ENEMY_EU_LIST.store( 95, 'Thryllak'        )
  ENEMY_EU_LIST.store( 96, 'Stonebeak'       )
  ENEMY_EU_LIST.store( 97, 'Razorbeak'       )
  ENEMY_EU_LIST.store( 98, 'Monstrum'        )
  ENEMY_EU_LIST.store( 99, 'Kantor'          )
  ENEMY_EU_LIST.store(100, 'Umbra'           )
  ENEMY_EU_LIST.store(101, 'Assassinata'     )
  ENEMY_EU_LIST.store(102, 'Executor'        )
  ENEMY_EU_LIST.store(103, 'Custodiae'       )
  ENEMY_EU_LIST.store(104, 'Veles'           )
  ENEMY_EU_LIST.store(105, 'Red Praeses'     )
  ENEMY_EU_LIST.store(106, 'Praeses Elite'   )
  ENEMY_EU_LIST.store(107, 'Jynnus'          )
  ENEMY_EU_LIST.store(108, 'Hydra'           )
  ENEMY_EU_LIST.store(109, 'Yulooper'        )
  ENEMY_EU_LIST.store(110, 'Hunta'           )
  ENEMY_EU_LIST.store(111, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(112, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(113, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(114, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(115, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(116, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(117, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(118, 'Hunta'           )
  ENEMY_EU_LIST.store(119, 'Delvax'          )
  ENEMY_EU_LIST.store(120, 'Hopril'          )
  ENEMY_EU_LIST.store(121, 'Elcian'          )
  ENEMY_EU_LIST.store(128, 'Antonio'         )
  ENEMY_EU_LIST.store(129, 'Sentinel'        )
  ENEMY_EU_LIST.store(130, 'Bleigock'        )
  ENEMY_EU_LIST.store(131, 'Carcer'          )
  ENEMY_EU_LIST.store(132, 'Galcian'         )
  ENEMY_EU_LIST.store(133, 'Sceptrum Praeses')
  ENEMY_EU_LIST.store(134, 'Rockwyrm'        )
  ENEMY_EU_LIST.store(136, 'Antonio 2'       )
  ENEMY_EU_LIST.store(137, 'Rik\'talish'     )
  ENEMY_EU_LIST.store(138, 'Sinistra'        )
  ENEMY_EU_LIST.store(139, 'Destra'          )
  ENEMY_EU_LIST.store(140, 'Ramirez'         )
  ENEMY_EU_LIST.store(141, 'Vigoro'          )
  ENEMY_EU_LIST.store(142, 'Dralkor Lacus'   )
  ENEMY_EU_LIST.store(144, 'Tortigar'        )
  ENEMY_EU_LIST.store(145, 'Jao'             )
  ENEMY_EU_LIST.store(146, 'Mao'             )
  ENEMY_EU_LIST.store(147, 'Muraji'          )
  ENEMY_EU_LIST.store(148, 'Veltarn'         )
  ENEMY_EU_LIST.store(149, 'Vigoro'          )
  ENEMY_EU_LIST.store(150, 'Dracoslyth'      )
  ENEMY_EU_LIST.store(151, 'Galcian'         )
  ENEMY_EU_LIST.store(152, 'Ramirez'         )
  ENEMY_EU_LIST.store(153, 'Ramirez'         )
  ENEMY_EU_LIST.store(154, 'Eliminator'      )
  ENEMY_EU_LIST.store(155, 'Gordo'           )
  ENEMY_EU_LIST.store(156, 'Furiosus'        )
  ENEMY_EU_LIST.store(157, 'Ramirez'         )
  ENEMY_EU_LIST.store(158, 'Piastol'         )
  ENEMY_EU_LIST.store(159, 'Piastol'         )
  ENEMY_EU_LIST.store(160, 'Piastol'         )
  ENEMY_EU_LIST.store(161, 'Piastol'         )
  ENEMY_EU_LIST.store(162, 'Piastol'         )
  ENEMY_EU_LIST.store(163, 'Piastol'         )
  ENEMY_EU_LIST.store(164, 'Piastol'         )
  ENEMY_EU_LIST.store(165, 'Piastol'         )
  ENEMY_EU_LIST.store(166, 'Piastol'         )
  ENEMY_EU_LIST.store(167, 'Piastol'         )
  ENEMY_EU_LIST.store(168, 'Piastol'         )
  ENEMY_EU_LIST.store(169, 'Piastol'         )
  ENEMY_EU_LIST.store(170, 'Piastol'         )
  ENEMY_EU_LIST.store(171, 'Piastol'         )
  ENEMY_EU_LIST.store(172, 'Piastol'         )
  ENEMY_EU_LIST.store(173, 'Piastol'         )
  ENEMY_EU_LIST.store(174, 'Piastol'         )
  ENEMY_EU_LIST.store(175, 'Piastol'         )
  ENEMY_EU_LIST.store(176, 'Piastol'         )
  ENEMY_EU_LIST.store(177, 'Piastol'         )
  ENEMY_EU_LIST.store(178, 'Tara'            )
  ENEMY_EU_LIST.store(179, 'Tara'            )
  ENEMY_EU_LIST.store(180, 'Tara'            )
  ENEMY_EU_LIST.store(181, 'Tara'            )
  ENEMY_EU_LIST.store(182, 'Tara'            )
  ENEMY_EU_LIST.store(183, 'Lira'            )
  ENEMY_EU_LIST.store(184, 'Lira'            )
  ENEMY_EU_LIST.store(185, 'Lira'            )
  ENEMY_EU_LIST.store(186, 'Lira'            )
  ENEMY_EU_LIST.store(187, 'Lira'            )
  ENEMY_EU_LIST.store(188, 'Pera'            )
  ENEMY_EU_LIST.store(189, 'Pera'            )
  ENEMY_EU_LIST.store(190, 'Pera'            )
  ENEMY_EU_LIST.store(191, 'Pera'            )
  ENEMY_EU_LIST.store(192, 'Pera'            )
  ENEMY_EU_LIST.store(193, 'Daikokuya'       )
  ENEMY_EU_LIST.store(194, 'Daikokuya'       )
  ENEMY_EU_LIST.store(195, 'Daikokuya'       )
  ENEMY_EU_LIST.store(196, 'Daikokuya'       )
  ENEMY_EU_LIST.store(197, 'Daikokuya'       )
  ENEMY_EU_LIST.store(198, 'Rupee'           )
  ENEMY_EU_LIST.store(199, 'Rupee'           )
  ENEMY_EU_LIST.store(200, 'Rupee'           )
  ENEMY_EU_LIST.store(201, 'Rupee'           )
  ENEMY_EU_LIST.store(202, 'Rupee'           )
  ENEMY_EU_LIST.store(203, 'Rupee'           )
  ENEMY_EU_LIST.store(204, 'Rupee'           )
  ENEMY_EU_LIST.store(205, 'Rupee'           )
  ENEMY_EU_LIST.store(206, 'Rupee'           )
  ENEMY_EU_LIST.store(207, 'Rupee'           )
  ENEMY_EU_LIST.store(208, 'Barta'           )
  ENEMY_EU_LIST.store(209, 'Barta'           )
  ENEMY_EU_LIST.store(210, 'Barta'           )
  ENEMY_EU_LIST.store(211, 'Barta'           )
  ENEMY_EU_LIST.store(212, 'Barta'           )
  ENEMY_EU_LIST.store(213, 'Vize'            )
  ENEMY_EU_LIST.store(214, 'Vize'            )
  ENEMY_EU_LIST.store(215, 'Vize'            )
  ENEMY_EU_LIST.store(216, 'Vize'            )
  ENEMY_EU_LIST.store(217, 'Vize'            )
  ENEMY_EU_LIST.store(218, 'Anita'           )
  ENEMY_EU_LIST.store(219, 'Anita'           )
  ENEMY_EU_LIST.store(220, 'Anita'           )
  ENEMY_EU_LIST.store(221, 'Anita'           )
  ENEMY_EU_LIST.store(222, 'Anita'           )
  ENEMY_EU_LIST.store(223, 'Faina'           )
  ENEMY_EU_LIST.store(224, 'Faina'           )
  ENEMY_EU_LIST.store(225, 'Faina'           )
  ENEMY_EU_LIST.store(226, 'Faina'           )
  ENEMY_EU_LIST.store(227, 'Faina'           )
  ENEMY_EU_LIST.store(228, 'Lord Bane'       )
  ENEMY_EU_LIST.store(229, 'Lord Bane'       )
  ENEMY_EU_LIST.store(230, 'Lord Bane'       )
  ENEMY_EU_LIST.store(231, 'Lord Bane'       )
  ENEMY_EU_LIST.store(232, 'Lord Bane'       )
  ENEMY_EU_LIST.store(233, 'Gunarm'          )
  ENEMY_EU_LIST.store(234, 'Gunarm'          )
  ENEMY_EU_LIST.store(235, 'Gunarm'          )
  ENEMY_EU_LIST.store(236, 'Gunarm'          )
  ENEMY_EU_LIST.store(237, 'Gunarm'          )
  ENEMY_EU_LIST.store(238, 'Vigoro'          )
  ENEMY_EU_LIST.store(239, 'Vigoro'          )
  ENEMY_EU_LIST.store(240, 'Vigoro'          )
  ENEMY_EU_LIST.store(241, 'Vigoro'          )
  ENEMY_EU_LIST.store(242, 'Vigoro'          )
  ENEMY_EU_LIST.store(243, 'DeathHound'      )
  ENEMY_EU_LIST.store(244, 'DeathHound'      )
  ENEMY_EU_LIST.store(245, 'DeathHound'      )
  ENEMY_EU_LIST.store(246, 'DeathHound'      )
  ENEMY_EU_LIST.store(247, 'Youjin'          )
  ENEMY_EU_LIST.store(248, 'Youjin'          )
  ENEMY_EU_LIST.store(249, 'Boo'             )
  ENEMY_EU_LIST.store(250, 'Boo'             )
  ENEMY_EU_LIST.store(251, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(252, 'Zivilyn Bane'    )
  ENEMY_EU_LIST.store(253, 'Frock'           )
  ENEMY_EU_LIST.store(254, 'Frock'           )

  # US names of enemies
  ENEMY_US_LIST = Hash.new('???')
  ENEMY_US_LIST.store(  0, 'Soldier'      )
  ENEMY_US_LIST.store(  1, 'Guard'        )
  ENEMY_US_LIST.store(  2, 'Seeker'       )
  ENEMY_US_LIST.store(  3, 'Marocca'      )
  ENEMY_US_LIST.store(  4, 'Grouder'      )
  ENEMY_US_LIST.store(  7, 'Spell Warden' )
  ENEMY_US_LIST.store(  8, 'Flestik'      )
  ENEMY_US_LIST.store(  9, 'Basallish'    )
  ENEMY_US_LIST.store( 10, 'Mind Stealer' )
  ENEMY_US_LIST.store( 11, 'Walrenk'      )
  ENEMY_US_LIST.store( 12, 'Varkris'      )
  ENEMY_US_LIST.store( 13, 'Azbeth'       )
  ENEMY_US_LIST.store( 14, 'Zivilyn Bane' )
  ENEMY_US_LIST.store( 15, 'Ghastling'    )
  ENEMY_US_LIST.store( 16, 'Florast'      )
  ENEMY_US_LIST.store( 17, 'Tsirat'       )
  ENEMY_US_LIST.store( 18, 'Thorkyn'      )
  ENEMY_US_LIST.store( 19, 'Scorfly'      )
  ENEMY_US_LIST.store( 20, 'Centralk'     )
  ENEMY_US_LIST.store( 21, 'Feralisk'     )
  ENEMY_US_LIST.store( 22, 'Ferlith'      )
  ENEMY_US_LIST.store( 23, 'Crylhound'    )
  ENEMY_US_LIST.store( 24, 'Magma Tiki'   )
  ENEMY_US_LIST.store( 25, 'Salamander'   )
  ENEMY_US_LIST.store( 26, 'Baroo'        )
  ENEMY_US_LIST.store( 27, 'Dung Fly'     )
  ENEMY_US_LIST.store( 28, 'Death\'s Head')
  ENEMY_US_LIST.store( 29, 'Looper'       )
  ENEMY_US_LIST.store( 30, 'Loopalon'     )
  ENEMY_US_LIST.store( 31, 'Tsurak'       )
  ENEMY_US_LIST.store( 32, 'Enforcer'     )
  ENEMY_US_LIST.store( 33, 'Serpentis'    )
  ENEMY_US_LIST.store( 34, 'Dralnog'      )
  ENEMY_US_LIST.store( 35, 'Que\'lak'     )
  ENEMY_US_LIST.store( 36, 'Pinalisk'     )
  ENEMY_US_LIST.store( 37, 'Crylbeast'    )
  ENEMY_US_LIST.store( 38, 'Slothstra'    )
  ENEMY_US_LIST.store( 39, 'Polraxis'     )
  ENEMY_US_LIST.store( 40, 'Roseln'       )
  ENEMY_US_LIST.store( 41, 'Elooper'      )
  ENEMY_US_LIST.store( 42, 'Grapor'       )
  ENEMY_US_LIST.store( 43, 'Sphyrus'      )
  ENEMY_US_LIST.store( 44, 'Iridzu'       )
  ENEMY_US_LIST.store( 45, 'Flyst'        )
  ENEMY_US_LIST.store( 46, 'Medulizk'     )
  ENEMY_US_LIST.store( 47, 'Lucich'       )
  ENEMY_US_LIST.store( 48, 'Digger'       )
  ENEMY_US_LIST.store( 49, 'Flat Fiend'   )
  ENEMY_US_LIST.store( 50, 'Burocca'      )
  ENEMY_US_LIST.store( 51, 'Drogerp'      )
  ENEMY_US_LIST.store( 52, 'Nadnarb'      )
  ENEMY_US_LIST.store( 53, 'Nairad'       )
  ENEMY_US_LIST.store( 54, 'Kanezl'       )
  ENEMY_US_LIST.store( 55, 'Mantoid'      )
  ENEMY_US_LIST.store( 56, 'Sorcerer'     )
  ENEMY_US_LIST.store( 57, 'Slithar'      )
  ENEMY_US_LIST.store( 58, 'Golooper'     )
  ENEMY_US_LIST.store( 59, 'Alusphere'    )
  ENEMY_US_LIST.store( 60, 'Soldier'      )
  ENEMY_US_LIST.store( 61, 'Delzool'      )
  ENEMY_US_LIST.store( 62, 'Defender'     )
  ENEMY_US_LIST.store( 63, 'Ghrost'       )
  ENEMY_US_LIST.store( 64, 'Graver'       )
  ENEMY_US_LIST.store( 65, 'Shrilp'       )
  ENEMY_US_LIST.store( 66, 'Cerosik'      )
  ENEMY_US_LIST.store( 67, 'Carnilak'     )
  ENEMY_US_LIST.store( 68, 'Valgand'      )
  ENEMY_US_LIST.store( 69, 'Berserker'    )
  ENEMY_US_LIST.store( 70, 'Lurgel Tank'  )
  ENEMY_US_LIST.store( 71, 'Tenkou'       )
  ENEMY_US_LIST.store( 72, 'Patrol Guard' )
  ENEMY_US_LIST.store( 73, 'Mine Patrol'  )
  ENEMY_US_LIST.store( 74, 'Forst Worm'   )
  ENEMY_US_LIST.store( 75, 'Destroyer'    )
  ENEMY_US_LIST.store( 76, 'Marauder'     )
  ENEMY_US_LIST.store( 77, 'Guardian'     )
  ENEMY_US_LIST.store( 78, 'Telsor'       )
  ENEMY_US_LIST.store( 79, 'Dorntak'      )
  ENEMY_US_LIST.store( 80, 'Linark'       )
  ENEMY_US_LIST.store( 81, 'Dolthstra'    )
  ENEMY_US_LIST.store( 82, 'Dracolurg'    )
  ENEMY_US_LIST.store( 83, 'Garagor'      )
  ENEMY_US_LIST.store( 84, 'Kilite'       )
  ENEMY_US_LIST.store( 85, 'Imezl'        )
  ENEMY_US_LIST.store( 86, 'Lurker'       )
  ENEMY_US_LIST.store( 87, 'Jellikra'     )
  ENEMY_US_LIST.store( 88, 'Scorpon'      )
  ENEMY_US_LIST.store( 89, 'Arclooper'    )
  ENEMY_US_LIST.store( 90, 'Tsorok'       )
  ENEMY_US_LIST.store( 91, 'Sentry'       )
  ENEMY_US_LIST.store( 92, 'Langry'       )
  ENEMY_US_LIST.store( 93, 'Durel Beetle' )
  ENEMY_US_LIST.store( 94, 'Totelm'       )
  ENEMY_US_LIST.store( 95, 'Thryllak'     )
  ENEMY_US_LIST.store( 96, 'Stonebeak'    )
  ENEMY_US_LIST.store( 97, 'Razorbeak'    )
  ENEMY_US_LIST.store( 98, 'Stalk Fiend'  )
  ENEMY_US_LIST.store( 99, 'Kantor'       )
  ENEMY_US_LIST.store(100, 'Shadow'       )
  ENEMY_US_LIST.store(101, 'Assassin'     )
  ENEMY_US_LIST.store(102, 'Officer'      )
  ENEMY_US_LIST.store(103, 'Mage Warden'  )
  ENEMY_US_LIST.store(104, 'Shock Troop'  )
  ENEMY_US_LIST.store(105, 'Red Guard'    )
  ENEMY_US_LIST.store(106, 'Elite Guard'  )
  ENEMY_US_LIST.store(107, 'Jynnus'       )
  ENEMY_US_LIST.store(108, 'Hydra Elite'  )
  ENEMY_US_LIST.store(109, 'Yulooper'     )
  ENEMY_US_LIST.store(110, 'Hunter'       )
  ENEMY_US_LIST.store(111, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(112, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(113, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(114, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(115, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(116, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(117, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(118, 'Hunter'       )
  ENEMY_US_LIST.store(119, 'Delvax'       )
  ENEMY_US_LIST.store(120, 'Hopril'       )
  ENEMY_US_LIST.store(121, 'Elcian'       )
  ENEMY_US_LIST.store(128, 'Antonio'      )
  ENEMY_US_LIST.store(129, 'Sentinel'     )
  ENEMY_US_LIST.store(130, 'Bleigock'     )
  ENEMY_US_LIST.store(131, 'Executioner'  )
  ENEMY_US_LIST.store(132, 'Galcian'      )
  ENEMY_US_LIST.store(133, 'Royal Guard'  )
  ENEMY_US_LIST.store(134, 'Rockwyrm'     )
  ENEMY_US_LIST.store(136, 'Antonio 2'    )
  ENEMY_US_LIST.store(137, 'Rik\'talish'  )
  ENEMY_US_LIST.store(138, 'Sinistra'     )
  ENEMY_US_LIST.store(139, 'Destra'       )
  ENEMY_US_LIST.store(140, 'Ramirez'      )
  ENEMY_US_LIST.store(141, 'Vigoro'       )
  ENEMY_US_LIST.store(142, 'Dralkor Tank' )
  ENEMY_US_LIST.store(144, 'Tortigar'     )
  ENEMY_US_LIST.store(145, 'Jao'          )
  ENEMY_US_LIST.store(146, 'Mao'          )
  ENEMY_US_LIST.store(147, 'Muraji'       )
  ENEMY_US_LIST.store(148, 'Veltarn'      )
  ENEMY_US_LIST.store(149, 'Vigoro'       )
  ENEMY_US_LIST.store(150, 'Dracoslyth'   )
  ENEMY_US_LIST.store(151, 'Galcian'      )
  ENEMY_US_LIST.store(152, 'Ramirez'      )
  ENEMY_US_LIST.store(153, 'Ramirez'      )
  ENEMY_US_LIST.store(154, 'Eliminator'   )
  ENEMY_US_LIST.store(155, 'Gordo'        )
  ENEMY_US_LIST.store(156, 'Mad Chef'     )
  ENEMY_US_LIST.store(157, 'Ramirez'      )
  ENEMY_US_LIST.store(158, 'Piastol'      )
  ENEMY_US_LIST.store(159, 'Piastol'      )
  ENEMY_US_LIST.store(160, 'Piastol'      )
  ENEMY_US_LIST.store(161, 'Piastol'      )
  ENEMY_US_LIST.store(162, 'Piastol'      )
  ENEMY_US_LIST.store(163, 'Piastol'      )
  ENEMY_US_LIST.store(164, 'Piastol'      )
  ENEMY_US_LIST.store(165, 'Piastol'      )
  ENEMY_US_LIST.store(166, 'Piastol'      )
  ENEMY_US_LIST.store(167, 'Piastol'      )
  ENEMY_US_LIST.store(168, 'Piastol'      )
  ENEMY_US_LIST.store(169, 'Piastol'      )
  ENEMY_US_LIST.store(170, 'Piastol'      )
  ENEMY_US_LIST.store(171, 'Piastol'      )
  ENEMY_US_LIST.store(172, 'Piastol'      )
  ENEMY_US_LIST.store(173, 'Piastol'      )
  ENEMY_US_LIST.store(174, 'Piastol'      )
  ENEMY_US_LIST.store(175, 'Piastol'      )
  ENEMY_US_LIST.store(176, 'Piastol'      )
  ENEMY_US_LIST.store(177, 'Piastol'      )
  ENEMY_US_LIST.store(178, 'Tara'         )
  ENEMY_US_LIST.store(179, 'Tara'         )
  ENEMY_US_LIST.store(180, 'Tara'         )
  ENEMY_US_LIST.store(181, 'Tara'         )
  ENEMY_US_LIST.store(182, 'Tara'         )
  ENEMY_US_LIST.store(183, 'Lira'         )
  ENEMY_US_LIST.store(184, 'Lira'         )
  ENEMY_US_LIST.store(185, 'Lira'         )
  ENEMY_US_LIST.store(186, 'Lira'         )
  ENEMY_US_LIST.store(187, 'Lira'         )
  ENEMY_US_LIST.store(188, 'Pera'         )
  ENEMY_US_LIST.store(189, 'Pera'         )
  ENEMY_US_LIST.store(190, 'Pera'         )
  ENEMY_US_LIST.store(191, 'Pera'         )
  ENEMY_US_LIST.store(192, 'Pera'         )
  ENEMY_US_LIST.store(193, 'Daikokuya'    )
  ENEMY_US_LIST.store(194, 'Daikokuya'    )
  ENEMY_US_LIST.store(195, 'Daikokuya'    )
  ENEMY_US_LIST.store(196, 'Daikokuya'    )
  ENEMY_US_LIST.store(197, 'Daikokuya'    )
  ENEMY_US_LIST.store(198, 'Rupee'        )
  ENEMY_US_LIST.store(199, 'Rupee'        )
  ENEMY_US_LIST.store(200, 'Rupee'        )
  ENEMY_US_LIST.store(201, 'Rupee'        )
  ENEMY_US_LIST.store(202, 'Rupee'        )
  ENEMY_US_LIST.store(203, 'Rupee'        )
  ENEMY_US_LIST.store(204, 'Rupee'        )
  ENEMY_US_LIST.store(205, 'Rupee'        )
  ENEMY_US_LIST.store(206, 'Rupee'        )
  ENEMY_US_LIST.store(207, 'Rupee'        )
  ENEMY_US_LIST.store(208, 'Barta'        )
  ENEMY_US_LIST.store(209, 'Barta'        )
  ENEMY_US_LIST.store(210, 'Barta'        )
  ENEMY_US_LIST.store(211, 'Barta'        )
  ENEMY_US_LIST.store(212, 'Barta'        )
  ENEMY_US_LIST.store(213, 'Vize'         )
  ENEMY_US_LIST.store(214, 'Vize'         )
  ENEMY_US_LIST.store(215, 'Vize'         )
  ENEMY_US_LIST.store(216, 'Vize'         )
  ENEMY_US_LIST.store(217, 'Vize'         )
  ENEMY_US_LIST.store(218, 'Anita'        )
  ENEMY_US_LIST.store(219, 'Anita'        )
  ENEMY_US_LIST.store(220, 'Anita'        )
  ENEMY_US_LIST.store(221, 'Anita'        )
  ENEMY_US_LIST.store(222, 'Anita'        )
  ENEMY_US_LIST.store(223, 'Faina'        )
  ENEMY_US_LIST.store(224, 'Faina'        )
  ENEMY_US_LIST.store(225, 'Faina'        )
  ENEMY_US_LIST.store(226, 'Faina'        )
  ENEMY_US_LIST.store(227, 'Faina'        )
  ENEMY_US_LIST.store(228, 'Lord Bane'    )
  ENEMY_US_LIST.store(229, 'Lord Bane'    )
  ENEMY_US_LIST.store(230, 'Lord Bane'    )
  ENEMY_US_LIST.store(231, 'Lord Bane'    )
  ENEMY_US_LIST.store(232, 'Lord Bane'    )
  ENEMY_US_LIST.store(233, 'Gunarm'       )
  ENEMY_US_LIST.store(234, 'Gunarm'       )
  ENEMY_US_LIST.store(235, 'Gunarm'       )
  ENEMY_US_LIST.store(236, 'Gunarm'       )
  ENEMY_US_LIST.store(237, 'Gunarm'       )
  ENEMY_US_LIST.store(238, 'Vigoro'       )
  ENEMY_US_LIST.store(239, 'Vigoro'       )
  ENEMY_US_LIST.store(240, 'Vigoro'       )
  ENEMY_US_LIST.store(241, 'Vigoro'       )
  ENEMY_US_LIST.store(242, 'Vigoro'       )
  ENEMY_US_LIST.store(243, 'DeathHound'   )
  ENEMY_US_LIST.store(244, 'DeathHound'   )
  ENEMY_US_LIST.store(245, 'DeathHound'   )
  ENEMY_US_LIST.store(246, 'DeathHound'   )
  ENEMY_US_LIST.store(247, 'Youjin'       )
  ENEMY_US_LIST.store(248, 'Youjin'       )
  ENEMY_US_LIST.store(249, 'Boo'          )
  ENEMY_US_LIST.store(250, 'Boo'          )
  ENEMY_US_LIST.store(251, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(252, 'Zivilyn Bane' )
  ENEMY_US_LIST.store(253, 'Frock'        )
  ENEMY_US_LIST.store(254, 'Frock'        )

end # class Translatable

# -- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --

end # module ALX
